version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - $PWD/jenkins_data:/var/jenkins_home
    networks:
      - net
  remote_host:
    container_name: remote-host
    image: remote-host
    build:
      context: remote-host
    restart: always
    volumes:
      - $PWD/remote-host_data:/var/project
    networks:
      - net
  nexus:
    container_name: nexus
    image: sonatype/nexus3
    restart: always
    ports:
      - "8081:8081"
      - "8082:8082"
    volumes:
      - $PWD/nexus_data:/nexus-data
    networks:
      - net
networks:
  net:
